import { ArrowUpRight, CheckCircle2 } from 'lucide-react'
import Link from 'next/link'
import { CtaBand, PageHero, SectionHeading, SiteShell } from '@/components/site'
import { services } from '@/lib/site-data'

const process = ['Understand the brief, constraints and success criteria', 'Develop a practical delivery approach and programme', 'Coordinate people, procurement, quality and safety', 'Deliver, review and support long-term value']

export default function ServicesPage() {
  return <SiteShell><main>
    <PageHero eyebrow="What we do" title="One experienced team from first brief to final handover." description="With years of expertise, NEGO delivers high-quality, innovative and cost-effective solutions for clients who need dependable construction and engineering partners." />
    <section className="container py-20 md:py-28"><SectionHeading eyebrow="Our capabilities" title="Built around the realities of delivery." description="Our services are designed to help clients move from ambition to completed work with fewer gaps between design, decisions and execution." /><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2">{services.map((service, index) => <article key={service.title} className="bg-background p-8 md:p-12"><p className="font-display text-5xl font-bold text-accent">0{index + 1}</p><h2 className="mt-16 text-3xl font-black">{service.title}</h2><p className="mt-5 max-w-lg text-lg leading-8 text-muted-foreground">{service.text}</p><p className="mt-5 max-w-lg leading-7 text-muted-foreground">{service.detail}</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] hover:text-accent">Discuss a project <ArrowUpRight /></Link></article>)}</div></section>
    <section className="bg-muted py-20 md:py-28"><div className="container grid gap-12 md:grid-cols-[.8fr_1.2fr] md:gap-24"><SectionHeading eyebrow="How we work" title="A clear process creates better outcomes." description="We bring the right conversations forward at the right time, so teams can make stronger decisions before issues become delays." /><div className="grid gap-4 sm:grid-cols-2">{process.map((item, index) => <article key={item} className="border border-border bg-background p-7"><span className="font-display text-3xl font-bold text-accent">0{index + 1}</span><p className="mt-10 text-base font-semibold leading-7">{item}</p></article>)}</div></div></section>
    <section className="container py-20 md:py-28"><SectionHeading eyebrow="What clients can expect" title="A partner that keeps the whole picture in view."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{['Technical judgement', 'Transparent communication', 'Quality-led execution', 'Safety-conscious planning', 'Programme discipline', 'Long-term value'].map((item) => <div key={item} className="flex items-center gap-3 border-b border-border py-5"><CheckCircle2 className="text-accent" /> <span className="font-semibold">{item}</span></div>)}</div></section>
  </main><CtaBand /></SiteShell>
}
