'use client'
import { FormEvent, useState } from 'react'
import { Mail, MapPin, Phone, Send } from 'lucide-react'
import { CtaBand, MediaSlot, PageHero, SectionHeading, SiteShell } from '@/components/site'
import { company } from '@/lib/site-data'

export default function ContactPage() { const [sent, setSent] = useState(false); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true) } return <SiteShell><main>
  <PageHero eyebrow="Contact NEGO" title="Tell us what you are building." description="We are happy to hear from you. Visit our office, give us a call or fill out the enquiry form to get a quick response from our team." />
  <section className="container grid gap-12 py-20 md:grid-cols-[1.1fr_.9fr] md:py-28"><form onSubmit={submit} className="flex flex-col gap-6 border border-border p-7 md:p-10"><div><p className="eyebrow text-accent">Start a conversation</p><h2 className="mt-4 text-3xl font-black">Tell us about your project.</h2><p className="mt-4 leading-7 text-muted-foreground">Share enough detail for us to understand the opportunity and the kind of support you need.</p></div><div className="grid gap-6 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-bold">First name<input required className="border border-input bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-2 text-sm font-bold">Last name<input required className="border border-input bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label></div><label className="flex flex-col gap-2 text-sm font-bold">Email<input required type="email" className="border border-input bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-2 text-sm font-bold">Phone number<input className="border border-input bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-2 text-sm font-bold">Inquiry<textarea required rows={7} placeholder="Write your message here..." className="border border-input bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label><button className="button-primary self-start" type="submit">{sent ? 'Enquiry received' : 'Submit enquiry'} <Send data-icon="inline-end" /></button>{sent && <p className="text-sm text-primary" role="status">Thanks — your enquiry is ready for the NEGO team to review.</p>}</form><aside className="flex flex-col gap-8"><div className="border border-border p-8 md:p-10"><p className="eyebrow text-accent">Find us</p><h2 className="mt-4 text-3xl font-black">{company.name}</h2><div className="mt-8 flex flex-col gap-6 text-sm leading-6 text-muted-foreground"><p className="flex gap-3"><MapPin className="shrink-0 text-accent" />{company.address}</p><p className="flex gap-3"><Phone className="shrink-0 text-accent" />{company.phones.join(' · ')}</p><p className="flex gap-3"><Mail className="shrink-0 text-accent" />hello@nego.example</p></div></div><MediaSlot label="Office/location map slot · supplied embed pending" tall /></aside></section>
  <section className="bg-muted py-20 md:py-28"><div className="container"><SectionHeading eyebrow="What happens next" title="A straightforward first conversation."/><div className="grid gap-4 md:grid-cols-3">{['We review your enquiry', 'We arrange a discovery conversation', 'We recommend the next practical step'].map((item, index) => <article key={item} className="border border-border bg-background p-8"><span className="font-display text-4xl font-bold text-accent">0{index + 1}</span><p className="mt-12 text-lg font-bold">{item}</p></article>)}</div></div></section>
</main><CtaBand /></SiteShell> }
